# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: EFront编译发布

on:
  push:
    branches:
      - develop

jobs:
  build-efront:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          rm -rf *.tgz
          rm .gitignore
          sudo npm pack

  public-efront:
    needs: build-efront
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
          if [ -f "public/efront.js" ];then
            sudo npm publish
          else
            exit 1
          fi
        shell: cmd
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
